config/routes.rb
Blocipedia::Application.routes.draw do

  get "collaborations/create"

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :charges

# /wikis/23/collaborations
# params :wiki_id

  resources :wikis do
    #resources :pages, except: [:index]
    resources :collaborations, only: [:new, :create]
  end

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    alias_action :edit, :to => :update
    #alias_action :new, :to => :create
    alias_action :update, :destroy, :to => :modify

    # if a member, they can manage their own pages 
    # (or create new ones)
    if user.role? :member
      can :manage, Wiki, :user_id => user.id
      can :manage, Wiki, :collaborations => { :user_id => user.id }
    end

    # Moderators can delete any post
    if user.role? :moderator
      can :modify, Wiki
    end

    if user.role? :premium
      can :manage, Wiki, :user_id => user.id
      can :manage, Collaboration
    end

    # Admins can do anything
    #if user.role? :admin
     # can :manage, :all
    #end

    can :read, Wiki, public: true
  end
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
  attr_accessible :user_id, :wiki_id
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
  attr_accessible :body, :title, :wiki

  default_scope order('created_at DESC')
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :collaborations
  
  has_many :wikis

  before_create :set_member
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessor :stripe_card_token

  ROLES = %w[member moderator premium admin]
  def role?(base_role)
    role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end

  def save_with_payment
      if valid?
        customer = Stripe::Customer.create(description: email, plan: 500, card: stripe_card_token)
        self.stripe_customer_token = customer.id
        save!
      end
  end 

  def active_for_authentication?
    true
  end

  private

  def set_member
    self.role = 'member'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :description, :name, :public
  has_many :collaborations
  has_many :users, through: :collaborations
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    Rails.logger.info ">>>> Current User: #{current_user}"
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    # update user to set premium to true
    current_user.update_attribute :role, "premium"

    redirect_to wikis_path, notice: "Thank you for subscribing! You can start creating wikis now."

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_filter :find_wiki

  def new
    @collaboration = Collaboration.new
  end

  def create
    @wiki.collaborations.delete_all
    @collaborations = []
    params[:collaboration][:user_id].each do |user_id|
      @collaborations << Collaboration.create(user_id: user_id, wiki_id: @wiki.id)
    end
    # loop through the params[:collaboration][:user_id].each
    # for each collaboration, create a new Collaboration object with the user_id and the @wiki_id (Collaboration.create(user_id: whatever, wiki_id: @wiki.id))
    # redirect to whereever you want to go
    redirect_to @wiki
  end  
    

  private 

  def find_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @page = Page.find(params[:id])
    @wiki = Wiki.find(params[:wiki_id])
  end

  def new
    @wiki = Wiki.find(params[:wiki_id])
    @page = Page.new
    authorize! :create, Page, message: "You need to be a member to create a new page."
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @page = current_user.pages.build(params[:page])
    @page.wiki = @wiki

    authorize! :create, @page, message: "You need to be signed up to do that."
    if @page.save
      redirect_to [@wiki, @page], notice: "Page was saved successfully."
    else
      flash[:error] = "There was an error saving the page. Please try again."
      render :new
  end
end

  def edit
    @wiki = Wiki.find(params[:wiki_id])
    @page = Page.find(params[:id])
    authorize! :edit, @page, message: "You need to own the page to edit it."
  end

  def update
    @wiki = Wiki.find(params[:wiki_id])
    @page = Page.find(params[:id])
    authorize! :update, @page, message: "You need to own the page to edit it."
    if @page.update_attributes(params[:page])
      redirect_to [@wiki, @page], notice: "Page was saved successfully."
    else
      flash[:error] = "There was an error saving the page. Please try again."
      render :edit
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    @user = User.new(params[:user])
    if @user.save
      if params[:premium]        
        sign_in(:user, @user)
        redirect_to new_charge_path
      else
        redirect_to root_path, :notice => "Check your email for confirmation instructions"
      end
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
  end

  def new
    @wiki = Wiki.new
    @wiki = current_user.wikis.build(params[:wiki])
    authorize! :create, @wiki, message: "You need to be signed up to create wikis."
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaboration = Collaboration.new
    @collaboration = current_user.collaborations.build(params[:collaboration])

  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize! :update, @wiki, message: "You need to own the wiki to update it."
  end

  def create
    @wiki = current_user.wikis.build(params[:wiki])
    authorize! :create, @wiki
    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize! :update, @wiki, message: "You need to own the wiki to update it."
    if @wiki.update_attributes(params[:wiki])
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error saving wiki. Please try again."
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/collaborations/_form.html.erb
<%= form_for [wiki, collaboration] do |f| %>
  <%# Grab all the users and iterate through them %>
  <% User.all.each do |user| %>
  <%# for each user, create a check box with that user's id %>
  
    <%= check_box_tag "collaboration[user_id][]", user.id, wiki.users.include?(user) %>
    <%# print the name of the user %>
    <%= user.name %>
  <%# end the loop %>
  <% end %>

<%= f.submit "Add collaborators", class: 'button' %>

<% end %>

app/views/collaborations/new.html.erb
<h1>Add Collaborators to <%= @wiki.name %></h1>


<%= render "form", wiki: @wiki, collaboration: @collaboration %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container"> 
    <div id="nav" class="sixteen columns">
      <ul>
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
           <% if current_user %>
             Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %>
           <% end %>
      </ul>
    </div>

      <% if flash[:notice] %>
        <div>
          <button>&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div>
          <button>&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div>
          <button>&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
  </div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
<div>
  <%= form_for [@wiki, @page] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/pages/new.html.erb
<h1>New Page</h1>
<div>
  <%= form_for [@wiki, @page] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<div class="row">
  <div class="span8">
    <p><%= @page.body %></p>
  </div>
  <div class="span4">
    <% if can? :edit, @page %>
      <%= link_to "Edit", edit_wiki_page_path(@wiki,@page), class: 'button' %>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: absingh</p>

app/views/welcome/index.html.erb
<div class="box-container">
  <h1>Blocipedia</h1>
  <h3>Social, Markdown Wikis</h3>

    <div class="column-left">
      <p>Public Wikis</p>
      <%= link_to "Free Plan", new_user_registration_path, class: 'button' %>
    </div>

    <div class="column-right">
      <p>Private Wikis</p>
      <%= link_to "Premium Plan", new_user_registration_path(premium: true), class: 'button' %>
    </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="span6">
    <%= form_for @wiki do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8 %>
        
        <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public wiki
          <% end %>

        <%= f.submit "Save", class: 'button' %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <div class="span8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.name, wiki %>
          </h4>
          <small>
            <%= wiki.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="span4">
    <% if can? :create, Wiki %>
      <%= link_to "New wiki", new_wiki_path, class: 'btn btn-large btn-block' %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

  <div>
    <%= form_for @wiki do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8 %>
        
        <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public wiki
            <% end %>
          <%= f.submit "Save", class: 'button' %>
    <% end %>
  </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.name %></h1>

<% if can? :update, @wiki %>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'button' %>
<% end %>

<div class="row">
  <div class="span8">
    <p><%= markdown @wiki.description %></p>
    
  </div>
  
</div>

<div class="row">
  <% if (@wiki.user == current_user) && (can? :manage, @collaboration) %>
  <%= render "collaborations/form", wiki: @wiki, collaboration: @collaboration %>
  <% end %>
</div>